install.packages("sf")
install.packages("raster")
install.packages("geojsonio")
install.packages("tidyverse")
install.packages("plyr")
install.packages("dplyr")
install.packages("purrr")
install.packages("jsonlite")
devtools::install_github("ReseauBiodiversiteQuebec/rcoleo")

install.packages("shiny")
install.packages("leaflet")
install.packages("shinydashboard")
install.packages("plotly")
